-- ================================================
-- DROP & CREATE Tablespaces + Users (GreenDelivery)
-- ================================================

-- ========================
-- ELIMINAR USUARIOS SI EXISTEN
-- ========================
BEGIN
    FOR rec IN (SELECT username FROM dba_users WHERE username IN ('LUIS','DAYRON','DUBAN')) LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || rec.username || ' CASCADE';
    END LOOP;
END;
/
-- ========================
-- ELIMINAR TABLESPACES SI EXISTEN
-- ========================
BEGIN
    FOR rec IN (SELECT tablespace_name 
                FROM dba_tablespaces 
                WHERE tablespace_name IN ('TBS_VENTAS','TBS_LOGISTICA','TBS_ADMIN')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLESPACE ' || rec.tablespace_name || ' INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ========================
-- CREACIÓN DE TABLESPACES
-- ========================
CREATE TABLESPACE TBS_VENTAS
    DATAFILE 'tbs_ventas.dbf' SIZE 200M 
    AUTOEXTEND ON NEXT 300M MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;
/

CREATE TABLESPACE TBS_LOGISTICA
    DATAFILE 'tbs_logistica.dbf' SIZE 200M 
    AUTOEXTEND ON NEXT 300M MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;
/

CREATE TABLESPACE TBS_ADMIN
    DATAFILE 'tbs_admin.dbf' SIZE 200M 
    AUTOEXTEND ON NEXT 300M MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;
/

-- ========================
-- CREACIÓN DE USUARIOS
-- ========================
CREATE USER Luis IDENTIFIED BY Ventas123
    DEFAULT TABLESPACE TBS_VENTAS 
    TEMPORARY TABLESPACE TEMP 
    QUOTA UNLIMITED ON TBS_VENTAS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE SEQUENCE, CREATE JOB, UNLIMITED TABLESPACE TO Luis;
/

CREATE USER Dayron IDENTIFIED BY Logistica123
    DEFAULT TABLESPACE TBS_LOGISTICA 
    TEMPORARY TABLESPACE TEMP 
    QUOTA UNLIMITED ON TBS_LOGISTICA;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE SEQUENCE, CREATE JOB, UNLIMITED TABLESPACE TO Dayron;
/

CREATE USER Duban IDENTIFIED BY Admin12345 
    DEFAULT TABLESPACE TBS_ADMIN 
    TEMPORARY TABLESPACE TEMP 
    QUOTA UNLIMITED ON TBS_ADMIN;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE SEQUENCE, CREATE JOB, UNLIMITED TABLESPACE TO Duban;
/

-- ========================
-- OTORGAR PERMISOS "ANY" A LUIS
-- ========================
GRANT CREATE ANY TABLE TO LUIS;
GRANT ALTER ANY TABLE TO LUIS;
GRANT DROP ANY TABLE TO LUIS;
GRANT SELECT ANY TABLE TO LUIS;
GRANT INSERT ANY TABLE TO LUIS;
GRANT UPDATE ANY TABLE TO LUIS;
GRANT DELETE ANY TABLE TO LUIS;

GRANT CREATE ANY SEQUENCE TO LUIS;
GRANT CREATE ANY INDEX TO LUIS;
GRANT CREATE ANY TRIGGER TO LUIS;
GRANT CREATE ANY VIEW TO LUIS;

-- ========================
-- ASIGNACIÓN DE PRIVILEGIOS ENTRE USUARIOS
-- ========================

-- Luis (Ventas) comparte CUSTOMER
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON LUIS.CUSTOMER TO DAYRON';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON LUIS.CUSTOMER TO DUBAN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Dayron (Logística) comparte DELIVERY
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DAYRON.DELIVERY TO LUIS';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DAYRON.DELIVERY TO DUBAN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Duban (Admin) comparte USERS
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DUBAN.USERS TO LUIS';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DUBAN.USERS TO DAYRON';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ========================
-- VERIFICACIONES
-- ========================
SELECT tablespace_name
FROM dba_tablespaces
WHERE tablespace_name IN ('TBS_VENTAS','TBS_LOGISTICA','TBS_ADMIN');

SELECT username
FROM all_users
WHERE username IN ('LUIS','DAYRON','DUBAN')
ORDER BY username;

SELECT owner, table_name
FROM all_tables
WHERE owner IN ('LUIS','DAYRON','DUBAN')
ORDER BY owner, table_name;


-- ================================
-- PERMISOS PARA LUIS
-- ================================
GRANT REFERENCES ON Duban.users TO Luis;
GRANT REFERENCES ON Duban.role TO Luis;

GRANT REFERENCES ON Dayron.vehicle TO Luis;
GRANT REFERENCES ON Dayron.driver TO Luis;
GRANT REFERENCES ON Dayron.route TO Luis;
GRANT REFERENCES ON Dayron.delivery TO Luis;
